data:
  csv_path: null
  cluster_cutoff: 500
  max_visits: 1
run:
  max_epochs: 11
  num_workers: 1
  run_name: IE_${run.max_epochs}
  debug: false
  seed: 5
task_name: BiG
paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  data_dir: ${paths.root_dir}/data/
  src_dir: ${paths.root_dir}/BiGGS/
  config_dir: ${paths.src_dir}/configs/
  sample_dir: ${paths.root_dir}/samples/
  ckpt_dir: ${paths.root_dir}/ckpt/
  log_dir: ${paths.root_dir}/logs/
  trained_model_dir: ${paths.root_dir}/BiGGS/trained_models/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: false
  enforce_tags: false
  print_config: true
experiment:
  predictor_dir: ${paths.ckpt_dir}/GFP/mutations_7/percentile_0.1_0.3/smoothed/predictor
  temperature: 0.01
  gibbs_samples: 100
  verbose: false
  ckpt_name: last.ckpt
